### ISSUE TITLE
No Cities for BC,NB,NF,NT,NS,PE?

### ISSUE THREAD

**Issue by GasparYYC** [vincentmorneau/oracle-geo-data#10]
Hi @vincentmorneau ,
 Seems the dataset omitted everything in half of the provinces.. :-(
C'mon.. Canada, is the centre of the universe, eh?  ;-)

**Comment by vincentmorneau** [comment]
I am in the process of moving to another data source: http://download.geonames.org/export/dump/

Thanks for watching.

**Comment by vincentmorneau** [comment]
Checked against new data source (publishing shortly). Cities are there.

**Comment by vincentmorneau** [comment]
fixed in https://github.com/vincentmorneau/oracle-countries-states-cities/commit/4ef3f9cfcf06d4cd27733da1a66e9ae9dbdc8baf
