### ISSUE TITLE
Neighborhood!

### ISSUE THREAD

**Issue by rimblas** [vincentmorneau/oracle-geo-data#11]
How about going down to a neighborhood?
https://www.yelp.com/developers/documentation/v2/neighborhood_list

Not as exact as cities, but sometimes it could be useful.

**Comment by vincentmorneau** [comment]
The city terminology is wrong anyway, as discussed in https://github.com/vincentmorneau/oracle-geo-data/issues/12, so I'll probably name that "Populated places", which will include cities and more (neiborhoods).

I'll close this in favor of https://github.com/vincentmorneau/oracle-geo-data/issues/12
