### ISSUE TITLE
Australian states/cities 

### ISSUE THREAD

**Issue by tschf** [vincentmorneau/oracle-geo-data#3]
Was just taking a look to see if my city was in there, and nope. In fact, if I go to the source site: http://www.iamrohit.in/countries-states-and-cities-database-of-world-in-mysql/, they have not one city for "New South Wales". 

In fact, the states they have listed are completely busted (as in most of them are cities)

![image](https://cloud.githubusercontent.com/assets/1747643/22714257/c48d4e86-eddf-11e6-9117-7d90da679cce.png)

**Comment by vincentmorneau** [comment]
Good to know. I tried to find a legit source but none are free. I may search for a better one later and update this repo.

**Comment by tschf** [comment]
I did a quick search before posting this, and there seem to be a couple of recommendations for geonames. It looks like the data comes in TSV, and is a single file for each country - so probably need some scripts to rework the model.

http://www.geonames.org/export/

(looks like its licensed under CCv3)

**Comment by vincentmorneau** [comment]
fixed in https://github.com/vincentmorneau/oracle-countries-states-cities/commit/4ef3f9cfcf06d4cd27733da1a66e9ae9dbdc8baf
