### ISSUE TITLE
Nationalities

### ISSUE THREAD

**Issue by Fatehcis** [vincentmorneau/oracle-geo-data#4]
Thanks for sharing,
It would be very helpful if you can add Nationalities

**Comment by vincentmorneau** [comment]
Example?

**Comment by Fatehcis** [comment]
insert into countries (country_id, code, name, phone_code,nationality) values (38, 'CA', 'Canada', 1,'Canadian');

**Comment by vincentmorneau** [comment]
Thanks for the suggestion, will look into it later.
