### ISSUE TITLE
Use more accurate/universal terminology than "states" and "cities"

### ISSUE THREAD

**Issue by skissane** [vincentmorneau/oracle-geo-data#9]
Many countries do not have first level subdivisions called "states", they use another term – such as province or region.

Even those who do have first level subdivisions called "states", often have other subdivisions at the same level lacking that name (e.g. Australia has both "states" and "territories")

I'd suggest a more universal term such as "first_level_subdivision".

You could also add a column "type_of_subdivision" to record the name for that type of subdivision where it is known – e.g. for Australia it might have the values "state" and "territory", for Canada it might have the values "province" and "territory", for New Zealand it would have the value "region", etc.

There is a similar issue with "cities" – the term "city" usually refers to an entity of a certain size, or having a certain legal status – the exact definition varies from country to country (and often involves some arbitrary historical factors.) I don't think you want to limit the list to places which are classified as "city", you really mean to include towns, villages, suburbs, etc – anywhere that people are likely to live – whatever their size or formal status. Consider instead a term such as "locality" as more general and globally accurate term than "city"

**Comment by vincentmorneau** [comment]
Absolutely agree. Again, I will incorporate this into a bigger data enhancement of this project.

**Comment by vincentmorneau** [comment]
I am thinking of going with "divisions" or "administrative_divisions".

**Comment by vincentmorneau** [comment]
fixed in https://github.com/vincentmorneau/oracle-countries-states-cities/commit/4ef3f9cfcf06d4cd27733da1a66e9ae9dbdc8baf
